### PR TITLE
Add and edit items

### PR DESCRIPTION
**Pull request by romgrk**
This implements an add/edit item feature.
Redmine issue: https://206.12.92.46/issues/278#change-783

@UlysseFG @jleblond who wants to be the reviewer for this one?

Reminders:
 - Might be good to add autocomplete for foreignkey fields (individual/sample/container ids)
 - I've hardcoded some of the server model choices (biospecimen type, sex, taxon). IDK if those are going to change often but if so, we need to ensure the server & client are kept in sync.

### CODE REVIEW

**Review by jleblond — COMMENTED** [review]
A few functional comments regarding the Add item feature:

 ** Regarding the Add Container page:
- the location field represents its parent container (if any), it would be best to choose from the existing containers, instead of a free text field. 
- Also I think Location and Coordinates should be made into a form sub-group representing the parent container
- Barcode is a mandatory field, it is indeed validated when submitting the form, but we could also add a red * visually
- Suggestion: For the fields Comment and Upd. Comment, maybe a larger text box would be more representative of the type of information we are collecting, in a similar way to the Django admin form
image
- Maybe have more explicit validation errors?
image

** Add Samples page
- Check for similar comments from Containers that could also be applied here
- Required fields are: Biospecimen type, name, individual (parent Individual), Reception date, Collection site, container (parent container)
- A sample may be extracted from another sample. Hence the Extracted From (parent Sample) optional field
- It is best to always display the unit of measure in a form (i.e. µL for volume used)
- In general I would refer you to the back-end form http://localhost:8000/fms_core/sample/add/ for additional instructions and comments on field (i.e. Volume used must be specified only for extracted nucleic acid samples)


** Individual page
- Label, taxon and sex are all mandatory fields
- Mother and Father are parents Individual (and optional)

**Comment by jleblond** [comment]
Parents related field text should be changed to meaningful text for the user. i.e. Name of the individual instead of its id
image

**Comment by jleblond** [comment]
Also in Add Sample,
for the Exp. group field.. by default we have an empty tag select in the Select Multiple field.. I had a similar issue in my search filters, in the Redux store, we cannot use an empty array 
image

- Volume history, is a field that is not displayed in the form, but it is a bJSON field representing the extractions.. should be dealt with, otherwise we get validation errors (volume history must not be null)

**Comment by romgrk** [comment]
I've applied the suggestions, everything is fixed except for volume_history.

I've noticed the django form still puts a Volume field and tries to create the first entry when volume is filled. I've tried to do the same thing [here](https://github.com/c3g/freezeman_web/pull/12/files#diff-f2ee49dbfada820ab90bd1b1f9fdad60e0c7cfc5cdb0c2175b697ea37b0c8fa3R302-R309) but it fails and I don't know what to pass to make volume_history be ok. Do you have any idea?

**Pull request merged**
