### PR TITLE
Replace loading by spinner

### PR DESCRIPTION
**Pull request by UlysseFG**
Spinner instead of "loading...". Pushing this to 3.1 so it doesn't disrupt release.

### CODE REVIEW

**Comment by jleblond** [comment]
Looks good, I would replace all the "loading..." text everywhere in the app by this Spin if you choose to use that one instead.
Also in terms of accessibility, it is good to have an alternate text in case the icon cant be found/cant be seen, which is why I would make a component out of it (which includes the Spin, and the alternate text)

**Comment by romgrk** [comment]
Haven't looked at the thing live but isn't it too overwhelming? Sometimes too much movement can be bad, a table full of spinners might be less ideal than a table full of "Loading...".

**Comment by UlysseFG** [comment]
The spinners are to my eye a bit easier and clearer than the loading text ... the spinners stay for a very short time but they are easier to understand than the loading text which has barely time to show up before being replaces which gives a blinking impression anyway.

I'm not sure we need to deal with alternate text since there is barely time to read whatever appears.

**Comment by jleblond** [comment]
Yes, it makes sense regarding the alternate text. I still think though that if we are to use spinners instead of 'loading...', itd be better to have that across all the app.

**Comment by UlysseFG** [comment]
I think i may have misunderstood part of your comment Jasmine ... I applied the change to everywhere in the app i could find with "loading..." but you mean make it the default behaviour whenever there is a loading element to show the spinner in the form of a spinner wrapper of sort? Maybe i am just not sure this will be desirable in each instance ...

**Comment by romgrk** [comment]
I wouldn't make it a hard rule, sometimes different loading indicators are better. Also don't forget we have [skeleton indicators](https://ant.design/components/skeleton/#components-skeleton-demo-element) which are also a really good choice for text

**Comment by jleblond** [comment]
What I meant is that another merge from master might be needed. Also I agree with Romain's idea about using skeleton indicators. If you are busy with your back-end work, maybe I can complete this PR for you today? @UlysseFG

**Pull request closed without merging**
